"""add parents table and chunk parent fk

Revision ID: 4b053c4ddbdc
Revises: 04420eed1df6
Create Date: 2026-09-25 17:04:42.819107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b053c4ddbdc'
down_revision: Union[str, None] = '04420eed1df6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parents',
    sa.Column('parent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_uuid', sa.UUID(), nullable=False),
    sa.Column('parent_text', sa.String(), nullable=False),
    sa.Column('parent_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_order', sa.Integer(), nullable=False),
    sa.Column('parent_project_id', sa.Integer(), nullable=False),
    sa.Column('parent_asset_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_asset_id'], ['assets.asset_id'], ),
    sa.ForeignKeyConstraint(['parent_project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('parent_id'),
    sa.UniqueConstraint('parent_uuid')
    )
    op.create_index('ix_parent_asset_id', 'parents', ['parent_asset_id'], unique=False)
    op.create_index('ix_parent_project_id', 'parents', ['parent_project_id'], unique=False)
    op.add_column('chunks', sa.Column('chunk_parent_id', sa.Integer(), nullable=False))
    op.create_index('ix_chunk_parent_id', 'chunks', ['chunk_parent_id'], unique=False)
    op.create_foreign_key('fk_chunks_parent_id', 'chunks', 'parents', ['chunk_parent_id'], ['parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chunks_parent_id', 'chunks', type_='foreignkey')
    op.drop_index('ix_chunk_parent_id', table_name='chunks')
    op.drop_column('chunks', 'chunk_parent_id')
    op.drop_index('ix_parent_project_id', table_name='parents')
    op.drop_index('ix_parent_asset_id', table_name='parents')
    op.drop_table('parents')
    # ### end Alembic commands ###
