APP_NAME="mini_rag"
VERSION="0.0.1"

FILE_ALLOWED_EXTENSIONS=["text/markdown", "text/x-markdown"]
FILE_MAX_SIZE=10485760
FILE_DEFAULT_CHUNK_SIZE=512000

POSTGRES_USERNAME="postgres"
POSTGRES_PASSWORD="<same-as-.env.postgres>"
POSTGRES_HOST="pgvector"
POSTGRES_PORT=5432
POSTGRES_MAIN_DATABASE="minirag"
POSTGRES_SSL=false

APP_API_KEY="<random-long-string>"

GENERATION_BACKEND="GEMINI"
GENERATION_MODEL_ID="gemini-3.8-flash"
GEMINI_API_KEY="<gemini-key>"
GEMINI_THINKING_BUDGET=2048
GEMINI_FALLBACK_MODELS="gemini-3.7-flash,gemini-3.6-flash"
GENERATION_FALLBACK_BACKEND="COHERE"
GENERATION_FALLBACK_MODEL_ID="command-a-03-2025"

EMBEDDING_BACKEND="COHERE"
EMBEDDING_MODEL_ID="embed-multilingual-v3.0"
EMBEDDING_MODEL_SIZE=1024
COHERE_API_KEY="<cohere-key>"

OPENAI_API_KEY=""
OPENAI_API_URL=""
OPENROUTER_API_KEY=""

INPUT_DAFAULT_MAX_CHARACTERS=8000
GENERATION_DAFAULT_MAX_TOKENS=2000
GENERATION_DAFAULT_TEMPERATURE=0.1

GROUNDED_MAX_OUTPUT_TOKENS=2000
GROUNDED_TEMPERATURE=0.2
GROUNDED_PRESENCE_PENALTY=0.3
GROUNDED_FREQUENCY_PENALTY=0.6
GROUNDING_MIN_RATIO=0.1
CONTEXT_WINDOW_CHILDREN=0

VECTOR_DB_BACKEND="PGVECTOR"
VECTOR_DB_PATH="qdrant_db"
VECTOR_DB_DISTANCE_METHOD="cosine"

RERANK_BACKEND="COHERE"
RERANK_MODEL_ID="rerank-v4.0-pro"
RERANK_CANDIDATES=20
RERANK_TARGET="chunk"
RERANK_MAX_CHARACTERS=10000

PRIMARY_LANG="ar"
DEFAULT_LANG="en"
